# -----------------------------------------------------------------------------
# [static]
# Creative and advanced static utility classes for your dx-styles project.
# -----------------------------------------------------------------------------
[static]

# -----------------------------------------------------------------------------
# [dynamic]
# Creative and advanced dynamic utility classes for your dx-styles project.
# -----------------------------------------------------------------------------
[dynamic]

# -----------------------------------------------------------------------------
# [generators]
# Creative and advanced generators for your dx-styles project.
# -----------------------------------------------------------------------------
[generators]

