# -----------------------------------------------------------------------------
# [static]
# More innovative and powerful static utility classes for your dx-styles project.
# -----------------------------------------------------------------------------
[static]

# -----------------------------------------------------------------------------
# [dynamic]
# More innovative and powerful dynamic utility classes for your dx-styles project.
# -----------------------------------------------------------------------------
[dynamic]

# -----------------------------------------------------------------------------
# [generators]
# More innovative and powerful generators for your dx-styles project.
# -----------------------------------------------------------------------------
[generators]
