# -----------------------------------------------------------------------------
# [static]
# New static utility classes for your dx-styles project.
# -----------------------------------------------------------------------------
[static]


# -----------------------------------------------------------------------------
# [dynamic]
# New dynamic utility classes for your dx-styles project.
# -----------------------------------------------------------------------------
[dynamic]

# -----------------------------------------------------------------------------
# [generators]
# New generators for your dx-styles project.
# -----------------------------------------------------------------------------
[generators]

