# -----------------------------------------------------------------------------
# [static]
# Even more static utility classes for your dx-styles project.
# -----------------------------------------------------------------------------
[static]


# -----------------------------------------------------------------------------
# [dynamic]
# Even more dynamic utility classes for your dx-styles project.
# -----------------------------------------------------------------------------
[dynamic]

# -----------------------------------------------------------------------------
# [generators]
# Even more generators for your dx-styles project.
# -----------------------------------------------------------------------------
[generators]
