# -----------------------------------------------------------------------------
# [static]
# Innovative and powerful static utility classes for your dx-styles project.
# -----------------------------------------------------------------------------
[static]


# -----------------------------------------------------------------------------
# [dynamic]
# Innovative and powerful dynamic utility classes for your dx-styles project.
# -----------------------------------------------------------------------------
[dynamic]

# -----------------------------------------------------------------------------
# [generators]
# Innovative and powerful generators for your dx-styles project.
# -----------------------------------------------------------------------------
[generators]

